services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama

  nodeapp:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - ollama

volumes:
  esdata:
  ollama-models:
